/*
 * Programación Avanzada: Programación por Capas.
 */
package gui.secretaria.administrar;

import Logica.ValidarEntradas;
import clases.Docente;
import gui.secretaria.VentanaSecretariaAdministrar;
import javax.swing.JOptionPane;
import logica.LogicaDocente;

/**
 *
 * @author Danilo Alejandro Ochoa Hidalgo
 */
public class AdministrarDocente extends javax.swing.JFrame {

    private LogicaDocente objLogicaDocente = new LogicaDocente();
    private Docente objDocente = new Docente();

    /**
     * Creates new form Docente
     */
    public AdministrarDocente() {
        initComponents();
        setLocationRelativeTo(null);
        this.entradasIniciales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLAdministrarDocente = new javax.swing.JLabel();
        jLCedula = new javax.swing.JLabel();
        jLNombres = new javax.swing.JLabel();
        jLApellidos = new javax.swing.JLabel();
        jLTelefono = new javax.swing.JLabel();
        jLMail = new javax.swing.JLabel();
        jTFCedula = new javax.swing.JTextField();
        jTFNombres = new javax.swing.JTextField();
        jTFApellidos = new javax.swing.JTextField();
        jTFTelefono = new javax.swing.JTextField();
        jTFMail = new javax.swing.JTextField();
        jBtnVolver = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jBtnModificar = new javax.swing.JButton();
        jBtnAgregar = new javax.swing.JButton();
        jBtnBuscar = new javax.swing.JButton();
        jLTitulo = new javax.swing.JLabel();
        jTFTitulo = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLAdministrarDocente.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLAdministrarDocente.setText("ADMINISTRAR DOCENTE");

        jLCedula.setText("Cédula");

        jLNombres.setText("Nombres");

        jLApellidos.setText("Apellidos");

        jLTelefono.setText("Teléfono");

        jLMail.setText("Mail");

        jBtnVolver.setText("Volver");
        jBtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVolverActionPerformed(evt);
            }
        });

        jBtnEliminar.setText("Eliminar");
        jBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarActionPerformed(evt);
            }
        });

        jBtnModificar.setText("Modificar");
        jBtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModificarActionPerformed(evt);
            }
        });

        jBtnAgregar.setText("Agregar");
        jBtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarActionPerformed(evt);
            }
        });

        jBtnBuscar.setText("Buscar");
        jBtnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnBuscarActionPerformed(evt);
            }
        });

        jLTitulo.setText("Título");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLCedula)
                    .addComponent(jLApellidos)
                    .addComponent(jLTelefono)
                    .addComponent(jLMail)
                    .addComponent(jLNombres)
                    .addComponent(jLTitulo))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTFCedula, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 281, Short.MAX_VALUE)
                    .addComponent(jTFTelefono)
                    .addComponent(jTFApellidos)
                    .addComponent(jTFNombres)
                    .addComponent(jTFMail)
                    .addComponent(jTFTitulo))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLAdministrarDocente)
                .addGap(215, 215, 215))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLAdministrarDocente)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTFCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnBuscar))
                        .addGap(9, 9, 9)
                        .addComponent(jTFNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTFApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(jLTelefono))
                                    .addComponent(jTFTelefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jTFMail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLMail)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jBtnAgregar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBtnModificar)
                                .addGap(11, 11, 11)
                                .addComponent(jBtnEliminar))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLCedula)
                        .addGap(20, 20, 20)
                        .addComponent(jLNombres)
                        .addGap(16, 16, 16)
                        .addComponent(jLApellidos)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLTitulo)
                            .addComponent(jTFTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                        .addComponent(jBtnVolver)
                        .addGap(26, 26, 26))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnBuscarActionPerformed
        // TODO add your handling code here:
        if (this.jTFCedula.isEnabled()) { // Flujo Normal
            if (!buscarDocente()) {
                this.entradasAgregar();
            } else {
                this.entradasEncontrado();
            }
        } else { // Flujo Alterno
            this.entradasIniciales();
        }

    }//GEN-LAST:event_jBtnBuscarActionPerformed

    private void jBtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarActionPerformed
        // TODO add your handling code here:
        if (!buscarDocente()) { // Flujo Normal

            if (this.validarEntradasSecretaria()) {

                if (objLogicaDocente.insertarDocente(objDocente)) {
                    JOptionPane.showMessageDialog(null, "Agregado Correctamente");
                    this.entradasIniciales();
                } else {
                    JOptionPane.showMessageDialog(null, "¡Fallo al Guardar!", "Error en BD", JOptionPane.ERROR_MESSAGE);
                }

            } else {
                JOptionPane.showMessageDialog(null, "¡Formato de Datos no Consistente!", "Información Personal", JOptionPane.ERROR_MESSAGE);
            }

        } else { // Flujo Alterno

            JOptionPane.showMessageDialog(null, "¡Ya Registrado!", "Duplicado", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_jBtnAgregarActionPerformed

    private void jBtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModificarActionPerformed
        // TODO add your handling code here:
        if (buscarDocente()) { // Flujo Normal

            this.entradasModificar();

            if (!this.jTFCedula.isEnabled()) {

                if (!compararDocente()) {

                    if (this.validarEntradasSecretaria()) {

                        if (objLogicaDocente.actualizarDocente(objDocente)) {
                            JOptionPane.showMessageDialog(null, "Actualizado Correctamente");
                            this.entradasIniciales();
                        } else {
                            JOptionPane.showMessageDialog(null, "¡Fallo al Guardar!", "Error en BD", JOptionPane.ERROR_MESSAGE);
                        }

                    } else {
                        JOptionPane.showMessageDialog(null, "¡Formato de Datos no Consistente!", "Información Personal", JOptionPane.ERROR_MESSAGE);
                    }

                } else {
                    JOptionPane.showMessageDialog(null, "Sin Cambios");
                }

            } else {
                JOptionPane.showMessageDialog(null, "¡No Encontrado!", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } else { // Flujo Alterno
            JOptionPane.showMessageDialog(null, "¡No Encontrado!", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_jBtnModificarActionPerformed

    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed
        // TODO add your handling code here:
        if (buscarDocente()) { // Flujo Normal

            this.entradasEliminar();

            if (!this.jTFCedula.isEnabled()) {

                int confirmacion = JOptionPane.showConfirmDialog(null, "¿Eliminar Permanentemente?", "¡Advertencia!", JOptionPane.ERROR_MESSAGE);
                if (confirmacion == JOptionPane.YES_OPTION) {

                    if (objLogicaDocente.eliminarDocente(objDocente)) {
                        JOptionPane.showMessageDialog(null, "Eliminado Correctamente");
                        this.entradasIniciales();
                    } else {
                        JOptionPane.showMessageDialog(null, "¡Fallo al Guardar!", "Error en BD", JOptionPane.ERROR_MESSAGE);
                    }

                } else {
                    this.entradasEncontrado();
                }

            } else {
                JOptionPane.showMessageDialog(null, "¡No Encontrado!", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } else { // Flujo Alterno

            JOptionPane.showMessageDialog(null, "¡No Encontrado!", "Error", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_jBtnEliminarActionPerformed

    private void jBtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVolverActionPerformed
        // TODO add your handling code here:
        VentanaSecretariaAdministrar ventanaRegistrar = new VentanaSecretariaAdministrar();
        ventanaRegistrar.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jBtnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdministrarDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdministrarDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdministrarDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdministrarDocente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdministrarDocente().setVisible(true);
            }
        });
    }

    // FUNCIONES PARA EL OBJETO MANIPULADO
    private boolean buscarDocente() {
        this.objDocente.setCedula(this.jTFCedula.getText());
        this.objDocente = objLogicaDocente.buscarDocente(objDocente);
        return this.objDocente.getCedula() != null; // return [true] si encuentra el objeto;
    }

    private boolean compararDocente() {
        Docente objAux = new Docente(objDocente.getIdDocente(),
                objDocente.getNombres(),
                objDocente.getApellidos(),
                objDocente.getCedula(),
                objDocente.getTelefono(),
                objDocente.getMail(),
                objDocente.getUsuario(),
                objDocente.getContrasena(),
                objDocente.getTitulo());

        objAux.setNombres(this.jTFNombres.getText());
        objAux.setApellidos(this.jTFApellidos.getText());
        objAux.setTelefono(this.jTFTelefono.getText());
        objAux.setMail(this.jTFMail.getText());
        objAux.setTitulo(this.jTFTitulo.getText());

        return objDocente.getNombres().equals(objAux.getNombres())
                && objDocente.getApellidos().equals(objAux.getApellidos())
                && objDocente.getTelefono().equals(objAux.getTelefono())
                && objDocente.getMail().equals(objAux.getMail())
                && objDocente.getTitulo().equals(objAux.getTitulo()); // return [true] si son iguales;
    }

    private boolean validarEntradasSecretaria() {
        if (this.validarEntradas()) {
            this.objDocente.setCedula(this.jTFCedula.getText());
            this.objDocente.setNombres(this.jTFNombres.getText());
            this.objDocente.setApellidos(this.jTFApellidos.getText());
            this.objDocente.setTelefono(this.jTFTelefono.getText());
            this.objDocente.setMail(this.jTFMail.getText());
            this.objDocente.setTitulo(this.jTFTitulo.getText());
            return true;
        } else {
            return false;
        }
    }

    private void presentarSecretaria() {
        this.jTFCedula.setText(this.objDocente.getCedula());
        this.jTFNombres.setText(this.objDocente.getNombres());
        this.jTFApellidos.setText(this.objDocente.getApellidos());
        this.jTFTelefono.setText(this.objDocente.getTelefono());
        this.jTFMail.setText(this.objDocente.getMail());
        this.jTFTitulo.setText(this.objDocente.getTitulo());
    }

    // OPCIONES DESPLEGADAS POR EVENTO PARA LA PANTALLA
    private void entradasVaciar() {
        this.jTFCedula.setText(null);
        this.jTFNombres.setText(null);
        this.jTFApellidos.setText(null);
        this.jTFTelefono.setText(null);
        this.jTFMail.setText(null);
        this.jTFTitulo.setText(null);
    }

    private void entradasIniciales() {
        this.entradasVaciar();

        this.jTFCedula.setEnabled(true);
        this.jTFNombres.setEnabled(false);
        this.jTFApellidos.setEnabled(false);
        this.jTFTelefono.setEnabled(false);
        this.jTFMail.setEnabled(false);
        this.jTFTitulo.setEnabled(false);

        this.jBtnAgregar.setEnabled(false);
        this.jBtnModificar.setEnabled(false);
        this.jBtnEliminar.setEnabled(false);
    }

    private void entradasEncontrado() {
        this.presentarSecretaria();

        this.jTFCedula.setEnabled(false);
        this.jTFNombres.setEnabled(false);
        this.jTFApellidos.setEnabled(false);
        this.jTFTelefono.setEnabled(false);
        this.jTFMail.setEnabled(false);
        this.jTFTitulo.setEnabled(false);

        this.jBtnAgregar.setEnabled(false);
        this.jBtnModificar.setEnabled(true);
        this.jBtnEliminar.setEnabled(true);
    }

    private void entradasAgregar() {
        this.jTFCedula.setEnabled(true);
        this.jTFNombres.setEnabled(true);
        this.jTFApellidos.setEnabled(true);
        this.jTFTelefono.setEnabled(true);
        this.jTFMail.setEnabled(true);
        this.jTFTitulo.setEnabled(true);

        this.jBtnAgregar.setEnabled(true);
        this.jBtnModificar.setEnabled(false);
        this.jBtnEliminar.setEnabled(false);
    }

    private void entradasModificar() {
        this.jTFCedula.setEnabled(false);
        this.jTFNombres.setEnabled(true);
        this.jTFApellidos.setEnabled(true);
        this.jTFTelefono.setEnabled(true);
        this.jTFMail.setEnabled(true);
        this.jTFTitulo.setEnabled(true);

        this.jBtnAgregar.setEnabled(false);
        this.jBtnModificar.setEnabled(true);
        this.jBtnEliminar.setEnabled(false);
    }

    private void entradasEliminar() {
        this.jTFCedula.setEnabled(false);
        this.jTFNombres.setEnabled(false);
        this.jTFApellidos.setEnabled(false);
        this.jTFTelefono.setEnabled(false);
        this.jTFMail.setEnabled(false);
        this.jTFTitulo.setEnabled(false);

        this.jBtnAgregar.setEnabled(false);
        this.jBtnModificar.setEnabled(false);
        this.jBtnEliminar.setEnabled(true);
    }

    // CONTROL DEL INGRESO DE DATOS CONSISTENTES
    private boolean validarEntradas() {
        ValidarEntradas objValidarEntradas = new ValidarEntradas();
        boolean correcto = false;
        if (objValidarEntradas.validarCedulas(this.jTFCedula.getText())) {
            if (objValidarEntradas.validarNombresApellidos(this.jTFNombres.getText())) {
                if (objValidarEntradas.validarNombresApellidos(this.jTFApellidos.getText())) {
                    if (objValidarEntradas.validarNumeroTelefono(this.jTFTelefono.getText())) {
                        if (objValidarEntradas.validarMail(this.jTFMail.getText())) {
                            if (objValidarEntradas.validarTitulos(this.jTFTitulo.getText())) {
                                correcto = true;
                            }
                        }
                    }
                }
            }
        }
        return correcto;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JButton jBtnBuscar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnModificar;
    private javax.swing.JButton jBtnVolver;
    private javax.swing.JLabel jLAdministrarDocente;
    private javax.swing.JLabel jLApellidos;
    private javax.swing.JLabel jLCedula;
    private javax.swing.JLabel jLMail;
    private javax.swing.JLabel jLNombres;
    private javax.swing.JLabel jLTelefono;
    private javax.swing.JLabel jLTitulo;
    private javax.swing.JTextField jTFApellidos;
    private javax.swing.JTextField jTFCedula;
    private javax.swing.JTextField jTFMail;
    private javax.swing.JTextField jTFNombres;
    private javax.swing.JTextField jTFTelefono;
    private javax.swing.JTextField jTFTitulo;
    // End of variables declaration//GEN-END:variables
}
