/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.secretaria;

import clases.Grado;
import clases.Materia;
import java.util.ArrayList;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import logica.LogicaGrado;

/**
 *
 * @author Danilo Alejandro Ochoa Hidalgo
 */
public class AgregarMateriasPorGrado extends javax.swing.JFrame {

    private LogicaGrado objLogicaGrado = new LogicaGrado();
    private ArrayList<Grado> objListadoGrados;
    private Grado objGrado;
    private Materia objMateria;

    /**
     * Creates new form AgregarGradoMateria
     */
    public AgregarMateriasPorGrado() {
        initComponents();
        setLocationRelativeTo(null);
        this.listarGrado();
        this.entradasIniciales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLGrado = new javax.swing.JLabel();
        jLAgregarMateriasPorGrado = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTbMaterias = new javax.swing.JTable();
        jBtnAgregar = new javax.swing.JButton();
        jBtnEliminar = new javax.swing.JButton();
        jBtnVolver = new javax.swing.JButton();
        jCBGrado = new javax.swing.JComboBox<>();
        jTFCodigo = new javax.swing.JTextField();
        jLCodigoDeMateria = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLGrado.setText("Grado");

        jLAgregarMateriasPorGrado.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLAgregarMateriasPorGrado.setText("AGREGAR MATERIAS POR GRADO");

        jTbMaterias.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Nombre", "Área"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTbMaterias.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTbMaterias);

        jBtnAgregar.setText("Agregar");
        jBtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarActionPerformed(evt);
            }
        });

        jBtnEliminar.setText("Eliminar");
        jBtnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEliminarActionPerformed(evt);
            }
        });

        jBtnVolver.setText("Volver");
        jBtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVolverActionPerformed(evt);
            }
        });

        jCBGrado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCBGradoActionPerformed(evt);
            }
        });

        jLCodigoDeMateria.setText("Código de Materia");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(jBtnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(160, 160, 160)
                            .addComponent(jBtnVolver))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 513, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLGrado)
                        .addGap(28, 28, 28)
                        .addComponent(jCBGrado, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLCodigoDeMateria)
                        .addGap(18, 18, 18)
                        .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLAgregarMateriasPorGrado)
                .addGap(133, 133, 133))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLAgregarMateriasPorGrado)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLGrado)
                    .addComponent(jCBGrado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTFCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnAgregar)
                    .addComponent(jLCodigoDeMateria))
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnVolver)
                    .addComponent(jBtnEliminar))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarActionPerformed
        // TODO add your handling code here:
        if (this.jTFCodigo.getText() != null) {

            if (this.jTFCodigo.getText().length() == 5) {

                this.objMateria = new Materia();
                this.objMateria.setCodigo(this.jTFCodigo.getText());

                if (buscarMateria()) {

                    Grado grado = new Grado();
                    grado.setIdGrado(objGrado.getIdGrado());
                    grado.setMaterias(new ArrayList<>());
                    grado.getMaterias().add(objMateria);

                    if (!comprobarGradoMateria(grado)) {

                        // Si el objGrado tiene una sola materia en el ArrayList<Materia>
                        if (grado.getMaterias().size() == 1) {

                            if (objLogicaGrado.insertarGradoMateria(grado)) {
                                JOptionPane.showMessageDialog(null, "Agregado Correctamente");
                                this.entradasAgregar();
                            } else {
                                JOptionPane.showMessageDialog(null, "¡Fallo al Guardar!", "Error en BD", JOptionPane.ERROR_MESSAGE);
                            }

                        }

                    } else {

                        JOptionPane.showMessageDialog(null, "¡Ya Registrado!", "Duplicado", JOptionPane.ERROR_MESSAGE);

                    }

                } else {

                    JOptionPane.showMessageDialog(null, "¡No Encontrado!", "Error", JOptionPane.ERROR_MESSAGE);

                }

            } else {

                JOptionPane.showMessageDialog(null, "¡Formato de Datos no Consistente!", "Información", JOptionPane.ERROR_MESSAGE);

            }

        }

    }//GEN-LAST:event_jBtnAgregarActionPerformed

    private void jBtnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEliminarActionPerformed
        // TODO add your handling code here:
        if (!this.jTbMaterias.getSelectionModel().isSelectionEmpty()) {

            int rowIndex = this.jTbMaterias.getSelectedRow();
            if (rowIndex >= 0 && rowIndex <= this.jTbMaterias.getColumnCount() - 1) {
                String codigo = String.valueOf(this.jTbMaterias.getValueAt(rowIndex, 0));
                this.objMateria = new Materia();
                this.objMateria.setCodigo(codigo);
                if (buscarMateria()) {
                    Grado grado = new Grado();
                    grado.setIdGrado(this.objGrado.getIdGrado());
                    grado.setMaterias(new ArrayList<>());
                    grado.getMaterias().add(this.objMateria);
                    if (objLogicaGrado.eliminarGradoMateria(grado)) {
                        JOptionPane.showMessageDialog(null, "Eliminado Correctamente");
                        this.entradasAgregar();
                    }
                }
            }

        } else {

            JOptionPane.showMessageDialog(null, "¡Seleccione un Campo!", "Información", JOptionPane.ERROR_MESSAGE);

        }

    }//GEN-LAST:event_jBtnEliminarActionPerformed

    private void jBtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVolverActionPerformed
        // TODO add your handling code here:
        VentanaSecretaria ventanaSecretaria = new VentanaSecretaria();
        ventanaSecretaria.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jBtnVolverActionPerformed

    private void jCBGradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCBGradoActionPerformed
        // TODO add your handling code here:
        if (this.jCBGrado.getSelectedItem() != null) {

            this.entradasAgregar();

        } else {

            this.entradasIniciales();

        }

    }//GEN-LAST:event_jCBGradoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AgregarMateriasPorGrado.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AgregarMateriasPorGrado.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AgregarMateriasPorGrado.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AgregarMateriasPorGrado.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AgregarMateriasPorGrado().setVisible(true);
            }
        });
    }

    // FUNCIONES PARA EL OBJETO MANIPULADO
    private boolean buscarMateria() {
        this.objMateria = objLogicaGrado.buscarMateria(objMateria);
        return this.objMateria.getCodigo() != null; // return [true] si encuentra el objeto;
    }

    private boolean comprobarGradoMateria(Grado grado) {
        Grado objAux = objLogicaGrado.comprobarGradoMateria(grado);
        return objAux.getMaterias() != null; // return [true] si encuentra el objeto;
    }

    // FUNCIONES PARA LISTAR
    private void listarGrado() {
        DefaultComboBoxModel comboBoxModel = new DefaultComboBoxModel();
        this.objListadoGrados = new ArrayList<>();

        comboBoxModel.addElement(null);

        this.objListadoGrados = objLogicaGrado.cargarGrados(objListadoGrados);
        this.objListadoGrados.forEach((grado) -> {
            comboBoxModel.addElement(grado);
        });

        this.jCBGrado.setModel(comboBoxModel);
    }

    private void listarMateria() {
        this.objGrado = new Grado();
        this.objGrado = (Grado) this.jCBGrado.getSelectedItem();
        this.objGrado.setMaterias(new ArrayList<>());
        this.objGrado = objLogicaGrado.cargarMaterias(objGrado);

        DefaultTableModel tableModel = (DefaultTableModel) this.jTbMaterias.getModel();
        tableModel.setRowCount(0);

        for (int i = 0; i < objGrado.getMaterias().size(); i++) {
            Object[] fila = new Object[tableModel.getColumnCount()];
            fila[0] = objGrado.getMaterias().get(i).getCodigo();
            fila[1] = objGrado.getMaterias().get(i).getNombre();
            fila[2] = objGrado.getMaterias().get(i).getArea();
            tableModel.addRow(fila);
        }

        obtenerEstilosTable();
    }

    private void obtenerEstilosTable() {

        for (int i = 0; i < this.jTbMaterias.getRowCount(); i++) {
            this.jTbMaterias.setRowHeight(i, 20);
        }

    }

    // OPCIONES DESPLEGADAS POR EVENTO PARA LA PANTALLA
    private void entradasVaciar() {
        DefaultTableModel tableModel = (DefaultTableModel) this.jTbMaterias.getModel();
        tableModel.setRowCount(0);
        if (this.jCBGrado.getItemCount() != 0) {
            this.jCBGrado.setSelectedIndex(0);
        }
        this.jTFCodigo.setText(null);
    }

    private void entradasIniciales() {
        this.entradasVaciar();

        this.jBtnAgregar.setEnabled(false);
        this.jBtnEliminar.setEnabled(false);
    }

    private void entradasAgregar() {
        this.listarMateria();

        this.jBtnAgregar.setEnabled(true);
        this.jBtnEliminar.setEnabled(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JButton jBtnEliminar;
    private javax.swing.JButton jBtnVolver;
    private javax.swing.JComboBox<String> jCBGrado;
    private javax.swing.JLabel jLAgregarMateriasPorGrado;
    private javax.swing.JLabel jLCodigoDeMateria;
    private javax.swing.JLabel jLGrado;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTFCodigo;
    private javax.swing.JTable jTbMaterias;
    // End of variables declaration//GEN-END:variables
}
