/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui.secretaria;

import gui.secretaria.administrar.AdministrarAnioLectivo;
import gui.secretaria.administrar.AdministrarDocente;
import gui.secretaria.administrar.AdministrarMateria;
import gui.secretaria.administrar.AdministrarParalelo;

/**
 *
 * @author Danilo Alejandro Ochoa Hidalgo
 */
public class VentanaSecretariaAdministrar extends javax.swing.JFrame {

    /**
     * Creates new form V
     */
    public VentanaSecretariaAdministrar() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnAdministrarMateria = new javax.swing.JButton();
        jBtnAdministrarParalelo = new javax.swing.JButton();
        jBtnAdministrarAnioLectivo = new javax.swing.JButton();
        jBtnVolver = new javax.swing.JButton();
        jLAdministrarRegistros = new javax.swing.JLabel();
        jBtnAdministrarDocente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jBtnAdministrarMateria.setText("Administrar Materia");
        jBtnAdministrarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAdministrarMateriaActionPerformed(evt);
            }
        });

        jBtnAdministrarParalelo.setText("Administrar Paralelo");
        jBtnAdministrarParalelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAdministrarParaleloActionPerformed(evt);
            }
        });

        jBtnAdministrarAnioLectivo.setText("Administrar Año Lectivo");
        jBtnAdministrarAnioLectivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAdministrarAnioLectivoActionPerformed(evt);
            }
        });

        jBtnVolver.setText("Volver");
        jBtnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVolverActionPerformed(evt);
            }
        });

        jLAdministrarRegistros.setFont(new java.awt.Font("Berlin Sans FB Demi", 0, 18)); // NOI18N
        jLAdministrarRegistros.setText("ADMINISTRAR");

        jBtnAdministrarDocente.setText("Administrar Docente");
        jBtnAdministrarDocente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAdministrarDocenteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnAdministrarDocente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnAdministrarMateria, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnAdministrarParalelo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnAdministrarAnioLectivo, javax.swing.GroupLayout.DEFAULT_SIZE, 215, Short.MAX_VALUE)
                    .addComponent(jBtnVolver, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLAdministrarRegistros)
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLAdministrarRegistros)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnAdministrarDocente, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnAdministrarMateria, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnAdministrarParalelo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBtnAdministrarAnioLectivo, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jBtnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnAdministrarDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAdministrarDocenteActionPerformed
        // TODO add your handling code here:
        AdministrarDocente registrarDocente = new AdministrarDocente();
        registrarDocente.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jBtnAdministrarDocenteActionPerformed

    private void jBtnAdministrarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAdministrarMateriaActionPerformed
        // TODO add your handling code here:
        AdministrarMateria registrarMateria = new AdministrarMateria();
        registrarMateria.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jBtnAdministrarMateriaActionPerformed

    private void jBtnAdministrarParaleloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAdministrarParaleloActionPerformed
        // TODO add your handling code here:
        AdministrarParalelo registrarParalelo = new AdministrarParalelo();
        registrarParalelo.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jBtnAdministrarParaleloActionPerformed

    private void jBtnAdministrarAnioLectivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAdministrarAnioLectivoActionPerformed
        // TODO add your handling code here:
        AdministrarAnioLectivo registrarAnioLectivo = new AdministrarAnioLectivo();
        registrarAnioLectivo.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jBtnAdministrarAnioLectivoActionPerformed

    private void jBtnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVolverActionPerformed
        // TODO add your handling code here:
        VentanaSecretaria ventanaSecretaria = new VentanaSecretaria();
        ventanaSecretaria.setVisible(true);
        this.dispose();

    }//GEN-LAST:event_jBtnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaSecretariaAdministrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaSecretariaAdministrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaSecretariaAdministrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaSecretariaAdministrar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>


        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaSecretariaAdministrar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAdministrarAnioLectivo;
    private javax.swing.JButton jBtnAdministrarDocente;
    private javax.swing.JButton jBtnAdministrarMateria;
    private javax.swing.JButton jBtnAdministrarParalelo;
    private javax.swing.JButton jBtnVolver;
    private javax.swing.JLabel jLAdministrarRegistros;
    // End of variables declaration//GEN-END:variables
}
